name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm install -g angular/cli && npm i angular-cli-ghpages --save-dev && ng build --prod --base-href "https://xxshubhamxx.github.io/gh-repo-scraper/" && npx angular-cli-ghpages --dir=dist/gh-repo-scraper

    # - name: Deploy
    #   if: success()
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: dist
    #     enable_jekyll: true